# fly.toml app configuration file generated for obi-x7j2la on 2026-05-08T13:04:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "obi-x7j2la"
primary_region = "lhr"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
